[package]
name = "rusty-duck"
version = "1.0.0"
edition = "2024"

[lib]
name = "rusty_duck"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[dependencies]
anyhow = "1.0.104"
axum = { version = "0.8.9", default-features = false, features = ["json", "query"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tower-service = { version = "0.3.3" }

worker = { version = "0.8.5", features = ["http", "axum"] }
worker-macros = { version = "0.8.5", features = ['http'] }

[dev-dependencies]
divan = "0.1.21"

[[bench]]
name = "bang-find"
harness = false
