name = "rusty-duck"
main = "build/index.js"
compatibility_date = "2026-08-15"

[build]
command = "cargo install -q worker-build && worker-build --release"

[observability]
enabled = false

[observability.logs]
enabled = false
persist = false
invocation_logs = false

[observability.traces]
enabled = false
persist = false
